// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMePf8wCBf5lHmBNZaoOnN8UbAtS7t55A',
    appId: '1:497053976903:web:27ffd3e8977adac78ce462',
    messagingSenderId: '497053976903',
    projectId: 'naru-c8575',
    authDomain: 'naru-c8575.firebaseapp.com',
    databaseURL: 'https://naru-c8575-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'naru-c8575.appspot.com',
    measurementId: 'G-DKMEE3BHQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdwfQN08PYImJdI3bdRuB8ntCNYxXXCWg',
    appId: '1:497053976903:android:fb6ee7c3d075b8638ce462',
    messagingSenderId: '497053976903',
    projectId: 'naru-c8575',
    databaseURL: 'https://naru-c8575-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'naru-c8575.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTx_8iG5MHLXV28BbIeWhXLWE-f-g4x_g',
    appId: '1:497053976903:ios:3023ddf258dc45778ce462',
    messagingSenderId: '497053976903',
    projectId: 'naru-c8575',
    databaseURL: 'https://naru-c8575-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'naru-c8575.appspot.com',
    androidClientId: '497053976903-1o0l41mn69dinqdvbic8bgd0salrngfj.apps.googleusercontent.com',
    iosClientId: '497053976903-c5uheg9hp68parta902nn2l8s2tljavj.apps.googleusercontent.com',
    iosBundleId: 'com.example.diabetest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTx_8iG5MHLXV28BbIeWhXLWE-f-g4x_g',
    appId: '1:497053976903:ios:3023ddf258dc45778ce462',
    messagingSenderId: '497053976903',
    projectId: 'naru-c8575',
    databaseURL: 'https://naru-c8575-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'naru-c8575.appspot.com',
    androidClientId: '497053976903-1o0l41mn69dinqdvbic8bgd0salrngfj.apps.googleusercontent.com',
    iosClientId: '497053976903-c5uheg9hp68parta902nn2l8s2tljavj.apps.googleusercontent.com',
    iosBundleId: 'com.example.diabetest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMePf8wCBf5lHmBNZaoOnN8UbAtS7t55A',
    appId: '1:497053976903:web:3ad25a2e08489c3a8ce462',
    messagingSenderId: '497053976903',
    projectId: 'naru-c8575',
    authDomain: 'naru-c8575.firebaseapp.com',
    databaseURL: 'https://naru-c8575-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'naru-c8575.appspot.com',
    measurementId: 'G-JRXH3CMTXE',
  );

}